### ISSUE TITLE
New operator framework 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/design#67] opened 2018-10-09 22:45 UTC
Create a navigational framework for all new operator tools that are full-page as a way to transition the operator experience to a full-page experience.

- Should include a left nav
- Top bar with login, dashboard link, alerts, and company logo

**Comment by cassytaylor** [comment] 2018-11-28 20:47
Duplicate of #64

**Closed as completed by cassytaylor** 2018-11-28 20:47 UTC
Labels: Epic
